### ISSUE TITLE
Remove site as additional input

### ISSUE THREAD

**Issue by TarekHC** [Eventdisplay/Converters#1]
Hi @GernotMaier 

Instead of adding the site as an additional input, I would identify automatically the site.

The easiest way that comes to my mind, is to create two arrays with all the CTA-N/S array name codes, and just identify the array codename. It would be trivial to add new array names in the future (and there will never be array names identical between CTA-N/S.

**Comment by GernotMaier** [comment]
yes, I was simply lazy. Also does it also assume at this point that it is the full array, and not e.g. the threshold arrays.

For now, I don't change anything and use them as they are. More important to get these files converted and forwarded to the users.

**Comment by GernotMaier** [comment]
This issue is address with pull request #13.
